function showError(message) {
  try {
    alert("message")
  }
  catch {
    console.log("message")
  }
  return null
}
